### ISSUE TITLE
Question: feasability of implementing for 3rd party VSCODE

### ISSUE THREAD

**Issue by jswhisperer** [robertohuertasm/vscode-open#81]
I've been having a tinker with your code and [code-server ](https://github.com/coder/code-server) to try and let a "browser based" vscode handle custom protocols and automatically open a git-repo / file.

So far I've adjusted the PWA of coder to this
```
{
  "name": "code-server",
  "short_name": "code-server",
  "start_url": ".",
  "display": "fullscreen",
  "display_override": ["window-controls-overlay"],
  "protocol_handlers": [
    {
      "protocol": "web+coder",
      "url": "/robertohuertasm.open-vscode?%s"
    }
  ],
  "description": "Run Code on a remote server.",
  "icons": [
    {
      "src": "./_static/src/browser/media/pwa-icon-192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "./_static/src/browser/media/pwa-icon-512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ]
}
```
I'm wondering if you had any ideas high level. I think my next step will be to modify code-server and add a route so your vscode ext can listen for the url?

Cheers

**Comment by robertohuertasm** [comment]
Hi @jswhisperer, I don't know much about code-server internals, but I guess that as long as it can recognize a particular schema and handle it, it should work.

**Comment by jswhisperer** [comment]
Ok thank you I think outside the scope of any specific extension after digging into their codebase... It's something on their end around handle external uri. Thank you for responding!
